services:
  app:
    container_name: streamsearch
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-develop}
    ports:
      - "3333:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-develop}
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: streamsearch-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
