services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV} # Pass NODE_ENV from the environment
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV} # Pass NODE_ENV to the container
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped